services:
  storiesque:
    build: "."
    ports:
      - 3000:3000
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5431:5432
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
