version: "3.9"
services:
  db:
    image: postgres
    container_name: "storiesque-db-dev"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./backend/sql/schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./backend/sql/trigger.sql:/docker-entrypoint-initdb.d/create_trigger.sql
