CREATE TABLE "user"
(
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(24) NOT NULL,
  password_hash VARCHAR(64) NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT false,
  email VARCHAR(128) NOT NULL
);

CREATE TABLE page
(
  id BIGSERIAL PRIMARY KEY,
  action VARCHAR(64) NOT NULL,
  body VARCHAR(4096) NOT NULL
);

CREATE TABLE story
(
  id BIGSERIAL PRIMARY KEY,
  title VARCHAR(48) NOT NULL,
  description VARCHAR(512),
  author BIGINT NOT NULL REFERENCES "user",
  first_page_id BIGINT REFERENCES page(id)
);

CREATE TABLE choices
(
  page_id BIGINT NOT NULL REFERENCES page(id) ON DELETE CASCADE,
  path_id BIGINT NOT NULL REFERENCES page(id) ON DELETE CASCADE
);
