CREATE TABLE "user"
(
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(24) NOT NULL,
  password_hash VARCHAR(64) NOT NULL,
  has_img BOOLEAN NOT NULL DEFAULT false,
  is_admin BOOLEAN NOT NULL DEFAULT false,
  email VARCHAR(128) NOT NULL
);

CREATE TABLE page
(
  id BIGSERIAL PRIMARY KEY,
  author BIGINT NOT NULL REFERENCES "user"(id),
  has_img BOOLEAN NOT NULL DEFAULT false,
  action VARCHAR(128) NOT NULL,
  body TEXT NOT NULL
);

CREATE TABLE story
(
  id BIGSERIAL PRIMARY KEY,
  title VARCHAR(48) NOT NULL,
  description VARCHAR(512),
  has_img BOOLEAN NOT NULL DEFAULT false,
  featured BOOLEAN NOT NULL DEFAULT false,
  author BIGINT NOT NULL REFERENCES "user"(id),
  first_page_id BIGINT REFERENCES page(id)
);

CREATE TABLE choices
(
  page_id BIGINT NOT NULL REFERENCES page(id) ON DELETE CASCADE,
  path_id BIGINT NOT NULL REFERENCES page(id) ON DELETE CASCADE
);

CREATE TABLE shelf
(
  owner_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  story_id BIGINT UNIQUE NOT NULL REFERENCES story(id) ON DELETE CASCADE,
  PRIMARY KEY (owner_id, story_id)
);