// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
)

type Choice struct {
	PageID int64
	PathID int64
}

type Page struct {
	ID     int64
	Author int64
	HasImg bool
	Action string
	Body   string
}

type Shelf struct {
	OwnerID int64
	StoryID int64
}

type Story struct {
	ID          int64
	Title       string
	Description sql.NullString
	HasImg      bool
	Featured    bool
	Author      int64
	FirstPageID sql.NullInt64
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	HasImg       bool
	IsAdmin      bool
	Email        string
}
