// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
)

type Page struct {
	ID    int64
	Title string
	Text  string
}

type Story struct {
	ID          int64
	Title       string
	Description sql.NullString
	FirstPageID sql.NullInt64
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	IsAdmin      bool
	Email        string
}
