// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: page.sql

package db

import (
	"context"
)

const createPage = `-- name: CreatePage :one
INSERT INTO page (title, body)
VALUES ($1, $2)
RETURNING id, title, body
`

type CreatePageParams struct {
	Title string
	Body  string
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRowContext(ctx, createPage, arg.Title, arg.Body)
	var i Page
	err := row.Scan(&i.ID, &i.Title, &i.Body)
	return i, err
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM page
WHERE id = $1
`

func (q *Queries) DeletePage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePage, id)
	return err
}

const getPage = `-- name: GetPage :one
SELECT id, title, body FROM page
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPage(ctx context.Context, id int64) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPage, id)
	var i Page
	err := row.Scan(&i.ID, &i.Title, &i.Body)
	return i, err
}

const updatePage = `-- name: UpdatePage :exec
UPDATE page
SET
  title = CASE WHEN $2::boolean
    THEN $3::VARCHAR(32) ELSE title END,

  body = CASE WHEN $4::boolean
    THEN $5::VARCHAR(4096) ELSE body END
WHERE id = $1
`

type UpdatePageParams struct {
	ID            int64
	TitleDoUpdate bool
	Title         string
	BodyDoUpdate  bool
	Body          string
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) error {
	_, err := q.db.ExecContext(ctx, updatePage,
		arg.ID,
		arg.TitleDoUpdate,
		arg.Title,
		arg.BodyDoUpdate,
		arg.Body,
	)
	return err
}
